### ISSUE TITLE
Not sure if an issue, but mainly a question.

### ISSUE THREAD

**Issue by Craigeniah** [turian/save-my-browser-tabs#1]
Will these files get deleted periodically, I had it set to a custom directory for a time, but if goes untouched for a while, it adds up quite a bit of files. I had 2+ gbs of data in the folder, and so I manually deleted it. Is there a way to make it only keep a certain number of entries, like maybe 5 at a time and have it delete the oldest ones once you've reached beyond that number. Just a suggestion/thought. 

I like the add on as it gives me a second backup to Firefox's sync, I've had my tabs erased and had no way of getting them back a few times. Thanks in advance for a response.

**Comment by SKelem** [comment]
1. Is there a way to get this add-on to create a backup only when the tabs change?
2. Failing that, is there a way to get the app not to create another backup if it's identical to the previous one?

**Comment by philt2001** [comment]
bloodcrow777
My fork (https://github.com/philt2001/save-my-browser-tabs) has an option to auto-delete files older than a certain date to keep the number of files small (and can write in HTML if required).

The xpi is repo ready to go.

**Comment by Craigeniah** [comment]
Thanks philt2001 that's awesome, just installed it manually! Will let you know if I have any issues while using it! =)

**Comment by turian** [comment]
@philt2001 That's great, I didn't realize you had forked it. If you want to submit a PR upstream, I'm happy to accept it.
